name: Check Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './README.md'
